import type { StandingsPayload } from "../hooks/useStandings";

// Fallback sample used only if the remote API fails to load.
export const SAMPLE_STANDINGS: StandingsPayload = {
  division: "C League",
  scrapedAt: "2025-10-04T10:03:11.241Z",
  source:
    "https://wpsl1.leaguerepublic.com/standingsForDate/262582567/2/-1/-1.html",
  standings: [
    {
      position: "",
      team: "Union Jack Club B",
      played: "4",
      won: "4",
      drawn: "0",
      lost: "0",
      gf: "40",
      ga: "6",
      gd: "",
      points: "4",
    },
    {
      position: "",
      team: "Mossbay Club B",
      played: "2",
      won: "2",
      drawn: "0",
      lost: "0",
      gf: "19",
      ga: "7",
      gd: "",
      points: "4",
      raw: ["2", "Mossbay Club B", "2", "2", "0", "0", "19", "7", "12", "4"],
    },
    {
      position: "",
      team: "Washhouse Miners",
      played: "2",
      won: "2",
      drawn: "0",
      lost: "0",
      gf: "16",
      ga: "10",
      gd: "",
      points: "4",
      raw: ["3", "Washhouse Miners", "2", "2", "0", "0", "16", "10", "6", "4"],
    },
    {
      position: "",
      team: "JJs E",
      played: "2",
      won: "1",
      drawn: "0",
      lost: "1",
      gf: "15",
      ga: "11",
      gd: "",
      points: "2",
      raw: ["4", "JJs E", "2", "1", "0", "1", "15", "11", "4", "2"],
    },
    {
      position: "",
      team: "Railway Club A",
      played: "2",
      won: "1",
      drawn: "0",
      lost: "1",
      gf: "13",
      ga: "13",
      gd: "",
      points: "2",
      raw: ["5", "Railway Club A", "2", "1", "0", "1", "13", "13", "0", "2"],
    },
    {
      position: "",
      team: "Vinies",
      played: "2",
      won: "1",
      drawn: "0",
      lost: "1",
      gf: "12",
      ga: "14",
      gd: "",
      points: "2",
      raw: ["6", "Vinies", "2", "1", "0", "1", "12", "14", "-2", "2"],
    },
    {
      position: "",
      team: "JJs D",
      played: "1",
      won: "0",
      drawn: "0",
      lost: "1",
      gf: "5",
      ga: "8",
      gd: "",
      points: "0",
      raw: ["7", "JJs D", "1", "0", "0", "1", "5", "8", "-3", "0"],
    },
    {
      position: "",
      team: "Grapes B",
      played: "1",
      won: "0",
      drawn: "0",
      lost: "1",
      gf: "4",
      ga: "9",
      gd: "",
      points: "0",
      raw: ["8", "Grapes B", "1", "0", "0", "1", "4", "9", "-5", "0"],
    },
    {
      position: "",
      team: "Roundabout",
      played: "2",
      won: "0",
      drawn: "0",
      lost: "2",
      gf: "9",
      ga: "17",
      gd: "",
      points: "0",
      raw: ["9", "Roundabout", "2", "0", "0", "2", "9", "17", "-8", "0"],
    },
    {
      position: "",
      team: "Union Jack Club",
      played: "2",
      won: "0",
      drawn: "0",
      lost: "2",
      gf: "4",
      ga: "22",
      gd: "",
      points: "0",
      raw: ["10", "Union Jack Club", "2", "0", "0", "2", "4", "22", "-18", "0"],
    },
  ],
};
